#!/usr/bin/env python3

import shlex
import argparse
import subprocess
from pathlib import Path


def call(cmd):
    print(" ".join(map(shlex.quote, cmd)))
    subprocess.call(cmd)


parser = argparse.ArgumentParser(
    description="Runs render and report with default arguments"
)
parser.add_argument(
    "--output", "-o",
    help="Output path",
    type=Path,
    default=Path("/tmp/report")
)
parser.add_argument(
    "--input-format", "-f",
    help="Input Format",
    default="json"
)
parser.add_argument(
    "command",
    nargs=argparse.REMAINDER,
    help="Renderer command"
)

args = parser.parse_args()
cmd_root = Path(__file__).parent
out_path = args.output / args.input_format
render_out = out_path / "images"
call([str(cmd_root / "render"), "-f", args.input_format, "-o", str(render_out)] + args.command)
call([str(cmd_root / "report"), str(render_out), "-o", str(out_path / "report.json"), "--html", str(out_path / "report.html")])
