#!/usr/bin/env python3

import sys
import shlex
import shutil
import argparse
import subprocess
from pathlib import Path

from script_utils import DirectoryScanner


def call(cmd):
    print(" ".join(map(shlex.quote, cmd)))
    subprocess.call([sys.executable] + cmd)


parser = argparse.ArgumentParser(
    description="Runs render and report with default arguments"
)
parser.add_argument(
    "--output", "-o",
    help="Output path",
    type=Path,
    default=Path("/tmp/report")
)
parser.add_argument(
    "--input-format", "-f",
    help="Input Format",
    default=[],
    action="append"
)
parser.add_argument(
    "--reference",
    type=Path,
    default=None,
)
parser.add_argument(
    "command",
    nargs=argparse.REMAINDER,
    help="Renderer command"
)

parser.add_argument(
    "--copy-reference",
    action="store_true",
    help="Copy reference images to the output directory",
)

parser.add_argument(
    "--label", "-l",
    help="Report label",
)

parser.add_argument(
    "--arg-placeholder", "-a",
    help="Argumant placeholder name for distinguishing render sets"
)

parser.add_argument(
    "--arg-value", "-v",
    default=[],
    action="append",
    help="Argumant value for distinguishing render sets"
)

args = parser.parse_args()
cmd_root = Path(__file__).parent
paths = []
formats = args.input_format or ["json"]
render_base = [str(cmd_root / "render")]
report_base = [str(cmd_root / "report")]
html_base = [str(cmd_root / "html-report")]
common = []
reference_path = cmd_root.parent / "data"
reference_out_path = args.output / "reference"
relative = None

if args.reference:
    reference_path /= args.reference
    common.append("--reference")
    common.append(str(reference_path))


if args.copy_reference:
    if args.reference:
        render_base += common
        common = []

    report_base.append("--reference")
    report_base.append(str(reference_out_path))
    report_base.append("--metadata")
    report_base.append(str(reference_path))
    report_base.append("--relative")
    relative = str(args.output)
    report_base.append(relative)

    print("Copying Files")
    ref_out_path = args.output / "reference"

    def copy_file(file: Path, relpath: Path):
        if "asset" not in file.name and file.suffix == ".png":
            out_file = ref_out_path / relpath
            out_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(file, out_file)

    DirectoryScanner(copy_file).scan(reference_path)
    print("")


if len(args.arg_value) > 0 and len(formats) > 1:
    sys.stderr.write("Only specify multiple formats or argument placeholders")
    sys.exit(1)


if len(args.arg_value) > 0:
    format = formats[0]
    index_placeholder = args.command.index(args.arg_placeholder)

    for value in args.arg_value:
        out_path = args.output / value
        render_out = out_path / "images"
        args.command[index_placeholder] = value
        call(render_base + common + ["-f", format, "-o", str(render_out), "-l", value] + args.command)
        paths.append(str(render_out))
        print("")
else:
    for format in formats:
        out_path = args.output / format
        render_out = out_path / "images"
        call(render_base + common + ["-f", format, "-o", str(render_out), "-l", args.label or format] + args.command)
        paths.append(str(render_out))
        print("")


basename = "report"
out_path = args.output

if len(formats) == 1 and len(args.arg_value) == 0:
    basename += "-" + formats[0]

report_filename = str(out_path / (basename + ".json"))
call(report_base + common + ["-o", report_filename] + paths)

html_cmd = html_base + [report_filename, "-o", str(out_path / (basename + ".html"))]
if relative:
    html_cmd += ["--relative", relative]
call(html_cmd)
