#!/usr/bin/env python3

import sys
import shlex
import argparse
import subprocess
from pathlib import Path


def call(cmd):
    print(" ".join(map(shlex.quote, cmd)))
    subprocess.call([sys.executable] + cmd)


parser = argparse.ArgumentParser(
    description="Runs render and report with default arguments"
)
parser.add_argument(
    "--output", "-o",
    help="Output path",
    type=Path,
    default=Path("/tmp/report")
)
parser.add_argument(
    "--input-format", "-f",
    help="Input Format",
    default=[],
    action="append"
)
parser.add_argument(
    "--reference",
    type=Path,
    default=None,
)
parser.add_argument(
    "command",
    nargs=argparse.REMAINDER,
    help="Renderer command"
)

args = parser.parse_args()
cmd_root = Path(__file__).parent
paths = []
formats = args.input_format or ["json"]
render_base = [str(cmd_root / "render")]
common = []

if args.reference:
    common.append("--reference")
    common.append(str(cmd_root.parent / "data" / args.reference))

for format in formats:
    out_path = args.output / format
    render_out = out_path / "images"
    call(render_base + common + ["-f", format, "-o", str(render_out), "-l", format] + args.command)
    paths.append(str(render_out))
    print("")


if len(formats) > 1:
    out_path = args.output


call([str(cmd_root / "report")] + common + ["-o", str(out_path / "report.json"), "--html", str(out_path / "report.html")] + paths)
