#!/usr/bin/env python3
import re
import sys
from pathlib import Path
from script_utils import Column, Table, DirectoryScanner


def collect_directory(file: Path, relpath: Path, found: dict):
    if "asset" not in file.name:
        basename = re.sub("-[0-9]+$", "", file.stem)
        if file.name.endswith("-meta.json"):
            basename = basename[:-5]
        example_name = str(relpath.parent / basename)
        found.setdefault(example_name, []).append(file.name)


data_root = Path(__file__).parent.parent / "data"
table = Table([
    Column("Example ID", "ljust"),
    Column("JSON"),
    Column("AEP"),
    Column("SVG"),
    Column("Meta"),
    Column("Frames", "rjust"),
])
has_json = 1
has_aep = 2
has_svg = 3
has_meta = 4
has_frames = 5
found = {}
file_count = 0
DirectoryScanner(collect_directory).scan(data_root, found)
for example, files in sorted(found.items()):
    row = [example, "NO", "NO", "NO", "NO", 0]
    for file in files:
        if file.endswith("-meta.json"):
            row[has_meta] = "X"
        elif file.endswith(".json"):
            file_count += 1
            row[has_json] = "X"
        elif file.endswith(".aep"):
            file_count += 1
            row[has_aep] = "X"
        elif file.endswith(".svg"):
            file_count += 1
            row[has_svg] = "X"
        elif re.match(".*-[0-9]+.png$", file):
            row[has_frames] += 1
    row[has_frames] = str(row[has_frames]) if row[has_frames] else "NO"
    table.row(row)

table.write()

sys.stdout.write("Total: %s tests %s files\n" % (len(found), file_count))
